//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDetailsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public Nullable<int> contact { get; set; }
        public string email { get; set; }
        public string department { get; set; }
        public string designation { get; set; }
        public Nullable<System.DateTime> dateofjoining { get; set; }
        public string address { get; set; }
    }
}
